service: photomnemonic

provider:
  name: aws
  runtime: nodejs10.x
  region: ${file(config.json):photomnemonic-region}
  stage: ${opt:stage, 'dev'}
  stackName: photomnemonic-${opt:stage, 'dev'}
  memorySize: 3008
  role: ${file(config.json):photomnemonic-iam-role}
  timeout: 90
  deploymentBucket:
    name: ${file(config.json):photomnemonic-bucket-id}
  vpc:
    securityGroupIds:
      - ${file(config.json):photomnemonic-security-group}
    subnetIds: ${file(config.json):photomnemonic-subnet-ids}
  resourcePolicy:
    - Effect: Allow
      Principal: "*"
      Action: execute-api:Invoke
      Resource:
        - execute-api:/*/*/*

functions:
  app:
    handler: index.handler
    events:
      - http:
          method: get
          path: screenshot
          contentHandling: CONVERT_TO_BINARY

plugins:
  - serverless-offline
  - serverless-apigw-binary
  - serverless-apigwy-binary

custom:
  apigwBinary:
    types:
      - '*/*'
